from atividade02 import*
#####TESTES
realizador = PessoaFisica('stefani','carol@com','88888888')
endereco = Endereco('Palmas','TO','405 NORTE','3','77002-018')
eventoA = Evento('nome', 'eventoPrincipal', 'sigla', 'dataHoraDeInicio', 'palavrasChave', 'logotipo', realizador, endereco)
eventoB = EventoCientifico('nome', 'eventoPrincipal', 'sigla', 'dataHoraDeInicio', 'palavrasChave', 'logotipo', realizador, endereco, 'issn')
artigoA = ArtigoCientifico('T1','evento')
artigoB = ArtigoCientifico('T2','evento')
autorA = Autor('carol', 'carol@mmgm.com','curicu')
autorB = Autor('stefani','jskaj','kkskak')
autorC = Autor('daniela','jskaj','kkskak')
autorD = Autor('suiara','jskaj','kkskak')
artigoA.addAutor(autorA)
artigoA.addAutor(autorB)
artigoB.addAutor(autorC)
artigoB.addAutor(autorD)
print(artigoA)
print(artigoB)
print(eventoA)
print(autorA)
print(autorB)